version: '3.8'

services:
  carconnectivity:
    build:
      context: .
      dockerfile: Containerfile
    networks:
      - carconnectivity-network
    volumes:
      - ./config:/app/config:ro
      - carconnectivity-data:/app
    ports:
      - "4000:4000"
    restart: unless-stopped

  grafana:
    build:
      context: .
      dockerfile: Containerfile.grafana
    env_file:
      - .env-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - carconnectivity-data:/home/grafana/.carconnectivity:ro
    networks:
      - carconnectivity-network
    ports:
      - "6000:3000"
    depends_on:
      - carconnectivity
    restart: unless-stopped

networks:
  carconnectivity-network:
    driver: bridge

volumes:
  carconnectivity-data:
  grafana-data:
